language: node_js
node_js:
  - '8'
  - '9'
os:
  - linux
  - osx

# Add ons to allow nodegit to compile
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev

install:
  # - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags` && ./install.sh) && nvm install $TRAVIS_NODE_VERSION && nvm use $TRAVIS_NODE_VERSION
  # - echo $PATH
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://github.com/jgm/pandoc/releases/download/1.19.2.1/pandoc-1.19.2.1-1-amd64.deb; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo dpkg -i pandoc-1.19.2.1-1-amd64.deb; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then HOMEBREW_NO_AUTO_UPDATE=1 brew install pandoc; fi
  # - npm install -g npm
  - npm i -g docsmith@beta
  - npm i -g

script:
  - mkdir workspace && cd workspace
  - safetag init --non-interactive
  - git clone https://github.com/SAFETAG/SAFETAG
  # Fix missing symlinks manually
  - safetag run --clean --no-watch --source $(pwd)/SAFETAG/en migrate
  # Link migrated content as content packages (use force for activities since for now there is a default activities package in safetag-toolkit)
  - safetag link ~/.content/packages/safetag-toolkit/content/.activities:~/.content/build/@safetag/migrate/activities --force
  - safetag link ~/.content/packages/safetag-toolkit/content/.references:~/.content/build/@safetag/migrate/references --force
  - safetag link ~/.content/packages/safetag-toolkit/content/.methods:~/.content/build/@safetag/migrate/methods --force
  - safetag link ~/.content/packages/safetag-toolkit/content/.images:~/.content/build/@safetag/migrate/images --force
  - safetag link ~/.content/packages/safetag-toolkit/content/.document_matter:~/.content/build/@safetag/migrate/document_matter --force
  - safetag link ~/.content/packages/safetag-toolkit/content/guide/index.md:~/.content/build/@safetag/migrate/index.guide.md --force
  # Build website
  - safetag start --clean --no-watch --baseurl /safetag/@safetag/toolkit toolkit
  - safetag start --clean --no-watch --baseurl /safetag/@safetag/guide guide
  - safetag start --clean --no-watch --baseurl /safetag/@safetag/browser browser

deploy:
  - provider: pages
    local_dir: /home/travis/.content/build
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    on:
      condition: $TRAVIS_OS_NAME = linux
      node: '8'

branches:
  only:
    - master
  except:
    - /^v[0-9]/
